import{a as E,S as P,i as d}from"./assets/vendor-frHSA4Lh.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const f=15,v="50294923-8c76cd495fb5b8c97be727835";async function y(r,e){const t="https://pixabay.com"+"/api/",o={key:v,q:r,page:e,per_page:f,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await E.get(t,{params:o})).data}function p(r){return r.map(({webformatURL:e,largeImageURL:n,tags:i,likes:t,views:o,comments:l,downloads:S})=>`
    <li class="photo-card">
      <a href="${n}" target="_blank">
        <img src="${e}" alt="${i}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${o}</p>
        <p><b>Comments:</b> ${l}</p>
        <p><b>Downloads:</b> ${S}</p>
      </div>
    </li>
    `).join("")}function B(r,e,n){r.innerHTML=p(e),n.refresh()}function q(r,e,n){r.insertAdjacentHTML("beforeend",p(e)),n.refresh()}function M(r){r.innerHTML=""}function m(r){r.classList.remove("is-hidden")}function b(r){r.classList.add("is-hidden")}function L(){a.loadBtn.classList.remove("is-hidden")}function h(){a.loadBtn.classList.add("is-hidden")}function u(){s<g?L():h()}const a={formEl:document.querySelector(".form"),galleryEl:document.querySelector(".gallery"),loader:document.querySelector(".loader-container"),loadBtn:document.querySelector(".load-btn")};let c,s=0,g=0;a.loadBtn.classList.add("is-hidden");const w=new P(".gallery a",{captionsData:"alt",captionDelay:250});a.formEl.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements["search-text"].value.trim(),!c){d.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}M(a.galleryEl),m(a.loader),s=1;try{console.log("НАДСИЛАЄМО ЗАПИТ",c,s);const e=await y(c,s);if(console.log("Відповідь:",e),e.hits.length===0){d.error({message:"Sorry, there are no images matching your search query.",position:"topRight"}),h();return}B(a.galleryEl,e.hits,w),g=Math.ceil(e.totalHits/f),console.log(g),u()}catch(e){d.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{b(a.loader),u(),r.target.reset()}});a.loadBtn.addEventListener("click",async r=>{console.log("Load button clicked, викликаю showLoader"),m(a.loader),s+=1;try{const e=await y(c,s);q(a.galleryEl,e.hits,w);const n=a.galleryEl.querySelector(".photo-card");if(n){const{height:t}=n.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}s*f>=e.totalHits?(h(),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch(e){d.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{b(a.loader),u()}});
//# sourceMappingURL=index.js.map
